name: psifos_mobile_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_dotenv: ^5.0.2
  http: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0

  # custom packages
  psifos_mobile_crypto:
    git:
      url: https://github.com/clcert/psifos_mobile_crypto.git
      ref: main
      
      # Uncomment below and replace 'your_commit_hash' with the desired commit hash, if needed
      # ref: your_commit_hash
      
      # Uncomment below and replace 'your_tag_name' with the desired tag, if needed
      # ref: your_tag_name


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
  - ".env"